<script setup>
import {ref,onMounted,onUnmounted} from 'vue';
import {webProjects} from '../data/projects.js';
const gallery=ref(null),atStart=ref(true),atEnd=ref(false);let resize;
function update(){const el=gallery.value;if(!el)return;atStart.value=el.scrollLeft<=2;atEnd.value=el.scrollLeft+el.clientWidth>=el.scrollWidth-2;}
function move(direction){const el=gallery.value;if(!el)return;el.scrollBy({left:direction*(el.querySelector('a').offsetWidth+16),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'});}
onMounted(()=>{resize=new ResizeObserver(update);resize.observe(gallery.value);update();});
onUnmounted(()=>resize?.disconnect());
</script>
<template>
<section data-chapter="projects" id="clientes" class="section-space projects-section" aria-labelledby="clientes-heading"><div class="section-shell"><h2 id="clientes-heading" class="section-title" data-text-reveal>Sistemas que acompañan<br>la operación real.</h2>
 <article class="femag-project" data-story-reveal><div class="femag-identity"><h3>FEMAG</h3><a href="https://femag.com.ar/" target="_blank" rel="noopener noreferrer" class="text-link">femag.com.ar</a><span class="project-status">Sistema a medida en desarrollo</span></div><div class="femag-details"><h4>Gestión operativa para una fábrica de fécula de mandioca.</h4><p>Estamos desarrollando una aplicación de escritorio conectada a MySQL para ordenar clientes, productos, transporte, órdenes de carga, remitos, cuenta corriente, permisos y auditoría.</p><ul><li>Aplicación local para 5/6 puestos en red interna</li><li>Dashboard central y menú operativo simple</li><li>Órdenes de carga y remitos imprimibles</li><li>Importación incremental desde MySQL y DBF</li></ul></div></article>
 <div class="gallery-heading" data-story-reveal><div><h3>Desarrollo web, con criterio comercial.</h3><p>Sitios para empresas y organizaciones que confiaron en nuestro trabajo.</p></div><div class="gallery-controls"><button type="button" :disabled="atStart" aria-label="Proyectos anteriores" aria-controls="web-projects" @click="move(-1)"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M19 12H5m6-6-6 6 6 6"/></svg></button><button type="button" :disabled="atEnd" aria-label="Proyectos siguientes" aria-controls="web-projects" @click="move(1)"><svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M5 12h14m-6-6 6 6-6 6"/></svg></button></div></div>
 <div ref="gallery" id="web-projects" class="web-gallery" @scroll.passive="update"><a v-for="project in webProjects" :key="project.url" :href="project.url" target="_blank" rel="noopener noreferrer" class="web-project" :aria-label="'Abrir sitio de '+project.name"><span>{{ project.type }}</span><h4>{{ project.name }}</h4><div>{{ project.url.replace('https://','').replace(/\/$/,'') }}<svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" aria-hidden="true"><path d="M7 17 17 7M7 7h10v10"/></svg></div></a></div>
 <a class="text-link projects-service" href="/desarrollo-web/">Conocer el servicio de desarrollo web</a>
</div></section>
</template>
<style scoped>
.projects-section{background:transparent}.femag-project{display:grid;grid-template-columns:.75fr 1.25fr;gap:60px;padding-block:48px;margin-top:44px;border-block:1px solid var(--color-border)}.femag-identity h3{font-size:58px;font-weight:700;letter-spacing:-.03em}.femag-identity>a{display:inline-block;margin-top:12px;font-size:14px}.project-status{display:block;margin-top:28px;color:var(--color-muted);font-size:13px}.femag-details h4{font-size:28px;max-width:30ch;line-height:1.2}.femag-details p{color:var(--color-muted);line-height:1.8;margin-top:20px}.femag-details ul{margin-top:24px;display:grid;grid-template-columns:1fr 1fr;gap:16px;font-size:14px;line-height:1.6}.gallery-heading{display:flex;align-items:flex-end;justify-content:space-between;gap:24px;margin-top:64px;margin-bottom:28px}.gallery-heading h3{font-size:30px;font-weight:600}.gallery-heading p{margin-top:12px;color:var(--color-muted)}.gallery-controls{display:flex;gap:10px}.gallery-controls button{width:48px;height:48px;border:1px solid var(--color-border);border-radius:8px;display:flex;align-items:center;justify-content:center}.gallery-controls button:disabled{opacity:.4;cursor:default}.web-gallery{display:flex;gap:16px;overflow-x:auto;scroll-snap-type:x proximity;padding:6px 4px 20px}.web-project{flex:0 0 calc((100% - 32px)/3);scroll-snap-align:start;border-radius:12px;background:var(--color-panel);padding:28px;min-height:260px;display:flex;flex-direction:column;transition:background-color 200ms ease-out}.web-project>span{font-size:14px;color:var(--color-muted)}.web-project h4{font-size:34px;font-weight:600;line-height:1.12;margin-block:28px 40px}.web-project>div{margin-top:auto;font-size:13px;color:var(--color-link);display:flex;align-items:center;justify-content:space-between;gap:12px}.web-project:hover{background:var(--color-surface)}.projects-service{display:inline-block;margin-top:24px;font-size:14px}
@media(max-width:1023px){.femag-project{gap:32px}.web-project{flex-basis:calc((100% - 16px)/2)}}
@media(max-width:639px){.femag-project{grid-template-columns:1fr;gap:28px;padding-block:32px}.femag-identity h3{font-size:44px}.femag-details ul{grid-template-columns:1fr}.gallery-heading h3{font-size:26px}.gallery-controls{display:none}.web-gallery{display:grid;overflow:visible;grid-template-columns:1fr;padding:4px}.web-project{min-height:170px;padding:24px}.web-project h4{font-size:24px;margin-block:16px 24px}}

@media(max-width:639px){.web-gallery{gap:0;padding:0}.web-project{min-height:0;padding:18px 0;border-radius:0;background:transparent;border-top:1px solid var(--color-border)}.web-project h4{font-size:22px;margin-block:8px 12px}.web-project>div{font-size:13px}.web-project:hover{background:transparent}.femag-details ul{gap:8px}.gallery-heading{margin-top:40px}.gallery-heading h3{font-size:24px}}
</style>
